import fs from 'node:fs';
import path from 'node:path';
import forge from 'node-forge';
import { config } from './config.js';

const pki=forge.pki;const certDir=path.dirname(config.certPath);fs.mkdirSync(certDir,{recursive:true});
const caKeys=pki.rsa.generateKeyPair(2048);const ca=pki.createCertificate();ca.publicKey=caKeys.publicKey;ca.serialNumber='01';ca.validity.notBefore=new Date();ca.validity.notAfter=new Date();ca.validity.notAfter.setFullYear(ca.validity.notBefore.getFullYear()+10);const caAttrs=[{name:'commonName',value:'Prestamos CDE Local CA'},{name:'organizationName',value:'Prestamos CDE'}];ca.setSubject(caAttrs);ca.setIssuer(caAttrs);ca.setExtensions([{name:'basicConstraints',cA:true},{name:'keyUsage',keyCertSign:true,digitalSignature:true}]);ca.sign(caKeys.privateKey,forge.md.sha256.create());
const keys=pki.rsa.generateKeyPair(2048);const cert=pki.createCertificate();cert.publicKey=keys.publicKey;cert.serialNumber='02';cert.validity.notBefore=new Date();cert.validity.notAfter=new Date();cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear()+3);const attrs=[{name:'commonName',value:config.lanHost},{name:'organizationName',value:'Prestamos CDE'}];cert.setSubject(attrs);cert.setIssuer(ca.subject.attributes);const altNames:any[]=[{type:2,value:'localhost'},{type:7,ip:'127.0.0.1'}];if(/^\d+\.\d+\.\d+\.\d+$/.test(config.lanHost))altNames.push({type:7,ip:config.lanHost});else altNames.push({type:2,value:config.lanHost});cert.setExtensions([{name:'basicConstraints',cA:false},{name:'keyUsage',digitalSignature:true,keyEncipherment:true},{name:'extKeyUsage',serverAuth:true},{name:'subjectAltName',altNames}]);cert.sign(caKeys.privateKey,forge.md.sha256.create());
fs.writeFileSync(path.join(certDir,'local-ca.crt'),pki.certificateToPem(ca));fs.writeFileSync(path.join(certDir,'local-ca.key'),pki.privateKeyToPem(caKeys.privateKey),{mode:0o600});fs.writeFileSync(config.certPath,pki.certificateToPem(cert));fs.writeFileSync(config.keyPath,pki.privateKeyToPem(keys.privateKey),{mode:0o600});console.log(`Certificados creados en ${certDir}. Instale local-ca.crt como autoridad confiable en cada dispositivo.`);
