import bcrypt from 'bcryptjs';
import { Decimal } from 'decimal.js';
import { DateTime } from 'luxon';
import { pool, transaction, type DbClient } from './db.js';
import { calculateFlatLoan, generateDueDates, type Frecuencia } from './finance.js';
import { config } from './config.js';

const permissions = [
  ['DASHBOARD_VER','Dashboard','Ver dashboard'],['CLIENTE_VER','Clientes','Ver clientes'],['CLIENTE_CREAR','Clientes','Crear clientes'],['CLIENTE_EDITAR','Clientes','Editar clientes'],
  ['PRESTAMO_VER','Préstamos','Ver préstamos'],['CALENDARIO_VER','Calendario','Ver calendario'],['CUOTA_NOTIFICAR','Calendario','Notificar cuotas'],['PRESTAMO_CREAR','Préstamos','Crear préstamos'],['PAGO_CREAR','Cobros','Registrar pagos'],['VENTA_CREAR','Ventas','Crear ventas'],
  ['PRODUCTO_EDITAR','Productos','Administrar productos'],['CAJA_VER','Caja','Ver caja'],['GASTO_CREAR','Gastos','Registrar gastos'],['ADMINISTRAR','Administración','Administrar sistema'],
] as const;

async function upsertCash(db:DbClient,date:string,user:number){const r=await db.query(`INSERT INTO caja(fecha,creado_por) VALUES($1,$2) ON CONFLICT(fecha) DO UPDATE SET activo=TRUE RETURNING idcaja`,[date,user]);return r.rows[0].idcaja;}

async function createDemoOperation(db:DbClient,user:number,input:{client:number;type:'PRESTAMO'|'VENTA_FINANCIADA';capital:string;rate:string;count:number;frequency:Frecuencia;start:string;daysWeek?:number[];daysMonth?:number[];paid:number;product?:number}){
  const calc=calculateFlatLoan(input.capital,input.rate,input.count);const dates=generateDueDates({fechaInicio:input.start,cantidadCuotas:input.count,frecuencia:input.frequency,diasSemana:input.daysWeek,diasMes:input.daysMonth});
  const op=await db.query(`INSERT INTO operacion_financiera(fk_idcliente,tipo,fecha_inicio,monto_capital,porcentaje_interes,monto_interes,monto_total,cantidad_cuotas,estado,observacion,creado_por) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'Operación de demostración',$10) RETURNING idoperacion_financiera`,[input.client,input.type,input.start,calc.capital,input.rate,calc.interest,calc.total,input.count,input.paid===input.count?'PAGADA':'ACTIVA',user]);const opId=op.rows[0].idoperacion_financiera;
  const plan=await db.query('INSERT INTO plan_pago(fk_idoperacion_financiera,frecuencia,creado_por) VALUES($1,$2,$3) RETURNING idplan_pago',[opId,input.frequency,user]);
  for(const day of input.daysWeek??[])await db.query('INSERT INTO plan_pago_dia_semana(fk_idplan_pago,dia_semana,creado_por) VALUES($1,$2,$3)',[plan.rows[0].idplan_pago,day,user]);
  for(const day of input.daysMonth??[])await db.query('INSERT INTO plan_pago_dia_mes(fk_idplan_pago,dia_mes,creado_por) VALUES($1,$2,$3)',[plan.rows[0].idplan_pago,day,user]);
  const cuotaIds:number[]=[];for(let i=0;i<input.count;i++){const q=calc.cuotas[i];const state=i<input.paid?'PAGADA':(dates[i]<DateTime.now().toISODate()!?'VENCIDA':'PENDIENTE');const result=await db.query('INSERT INTO cuota(fk_idoperacion_financiera,numero,fecha_vencimiento,monto_capital,monto_interes,monto_total,estado,creado_por) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING idcuota',[opId,i+1,dates[i],q.montoCapital,q.montoInteres,q.montoTotal,state,user]);cuotaIds.push(result.rows[0].idcuota);}
  let loanId:number|null=null;if(input.type==='PRESTAMO'){const p=await db.query('INSERT INTO prestamo(fk_idoperacion_financiera,fecha_desembolso,creado_por) VALUES($1,$2,$3) RETURNING idprestamo',[opId,input.start,user]);loanId=p.rows[0].idprestamo;const cash=await upsertCash(db,input.start,user);await db.query(`INSERT INTO movimiento_caja(fk_idcaja,fk_idprestamo,tipo,monto,concepto,fecha_movimiento,creado_por) VALUES($1,$2,'EGRESO',$3,'Desembolso de préstamo demo',$4,$5)`,[cash,loanId,calc.capital,`${input.start} 10:00:00`,user]);}else await db.query('INSERT INTO venta_financiada(fk_idoperacion_financiera,fk_idproducto,cantidad,precio_unitario,precio_contado,creado_por) VALUES($1,$2,1,$3,$3,$4)',[opId,input.product,input.capital,user]);
  if(input.paid>0){const total=calc.cuotas.slice(0,input.paid).reduce((s,q)=>s.plus(q.montoTotal),new Decimal(0));const form=await db.query(`SELECT idforma_pago FROM forma_pago WHERE codigo='EFECTIVO'`);const payDate=DateTime.now().minus({days:2}).toFormat('yyyy-MM-dd HH:mm:ss');const payment=await db.query(`INSERT INTO pago(fk_idoperacion_financiera,fk_idforma_pago,fecha_pago,monto,estado,referencia,creado_por) VALUES($1,$2,$3,$4,'CONFIRMADO','DEMO',$5) RETURNING idpago`,[opId,form.rows[0].idforma_pago,payDate,total.toFixed(2),user]);for(let i=0;i<input.paid;i++){const q=calc.cuotas[i];await db.query('INSERT INTO pago_aplicacion(fk_idpago,fk_idcuota,monto_interes,monto_capital,creado_por) VALUES($1,$2,$3,$4,$5)',[payment.rows[0].idpago,cuotaIds[i],q.montoInteres,q.montoCapital,user]);}const date=DateTime.fromSQL(payDate).toISODate()!;const cash=await upsertCash(db,date,user);await db.query(`INSERT INTO movimiento_caja(fk_idcaja,fk_idpago,tipo,monto,concepto,fecha_movimiento,creado_por) VALUES($1,$2,'INGRESO',$3,'Cobro de cuotas demo',$4,$5)`,[cash,payment.rows[0].idpago,total.toFixed(2),payDate,user]);}
  return {opId,loanId};
}

async function seed(){
  const reset=process.argv.includes('--reset-demo');if(reset&&process.env.CONFIRM_RESET_DEMO!=='SI')throw new Error('Para reiniciar la demo use CONFIRM_RESET_DEMO=SI npm run db:seed:reset-demo');
  await transaction(async db=>{
    if(reset)await db.query(`TRUNCATE movimiento_caja,gasto,pago_aplicacion,pago,garantia,operacion_usuario,cuota,plan_pago_dia_mes,plan_pago_dia_semana,plan_pago,venta_financiada,prestamo,operacion_financiera,cliente_archivo,cliente_referencia,cliente,producto,propietario_banco,banco,propietario,archivo,configuracion_financiera,forma_pago,gasto_tipo,rol_evento,evento,usuario,rol,caja RESTART IDENTITY CASCADE`);
    const existing=await db.query(`SELECT idusuario FROM usuario WHERE LOWER(login)='admin@prestamos.local'`);if(existing.rows[0]){console.log('Datos demo ya cargados; no se realizaron duplicados.');return;}
    await db.query('SET CONSTRAINTS ALL DEFERRED');const reserved=(await db.query(`SELECT nextval('usuario_idusuario_seq') AS id`)).rows[0].id;const adminRole=(await db.query(`INSERT INTO rol(nombre,descripcion,creado_por) VALUES('Administrador','Acceso completo',$1) RETURNING idrol`,[reserved])).rows[0].idrol;const hash=await bcrypt.hash('Prestamo2026!',12);await db.query(`INSERT INTO usuario(idusuario,fk_idrol,login,password_hash,nombres,apellidos,cedula,email,creado_por) VALUES($1,$2,'admin@prestamos.local',$3,'Administrador','Sistema','1000000','admin@prestamos.local',NULL)`,[reserved,adminRole,hash]);const admin=Number(reserved);await db.query('UPDATE usuario SET creado_por=$1 WHERE idusuario=$1',[admin]);
    const familiarType=(await db.query(`INSERT INTO tipo_referencia(nombre,descripcion,orden,creado_por) VALUES('Familiar','Referencia familiar',1,$1) ON CONFLICT(nombre) DO UPDATE SET activo=TRUE RETURNING idtipo_referencia`,[admin])).rows[0].idtipo_referencia;const amistadType=(await db.query(`INSERT INTO tipo_referencia(nombre,descripcion,orden,creado_por) VALUES('Amistad','Referencia de amistad',2,$1) ON CONFLICT(nombre) DO UPDATE SET activo=TRUE RETURNING idtipo_referencia`,[admin])).rows[0].idtipo_referencia;
    const collector=(await db.query(`INSERT INTO rol(nombre,descripcion,creado_por) VALUES('Cobrador','Clientes y cobros',$1) RETURNING idrol`,[admin])).rows[0].idrol;const viewer=(await db.query(`INSERT INTO rol(nombre,descripcion,creado_por) VALUES('Consulta','Solo lectura',$1) RETURNING idrol`,[admin])).rows[0].idrol;
    const eventIds=new Map<string,number>();for(const [code,module,name] of permissions){const e=await db.query('INSERT INTO evento(codigo,modulo,nombre,creado_por) VALUES($1,$2,$3,$4) RETURNING idevento',[code,module,name,admin]);eventIds.set(code,e.rows[0].idevento);await db.query('INSERT INTO rol_evento(fk_idrol,fk_idevento,permitido,creado_por) VALUES($1,$2,TRUE,$3)',[adminRole,e.rows[0].idevento,admin]);if(['DASHBOARD_VER','CLIENTE_VER','CLIENTE_CREAR','CLIENTE_EDITAR','PRESTAMO_VER','CALENDARIO_VER','CUOTA_NOTIFICAR','PAGO_CREAR','CAJA_VER'].includes(code))await db.query('INSERT INTO rol_evento(fk_idrol,fk_idevento,permitido,creado_por) VALUES($1,$2,TRUE,$3)',[collector,e.rows[0].idevento,admin]);if(['DASHBOARD_VER','CLIENTE_VER','PRESTAMO_VER','CALENDARIO_VER','CAJA_VER'].includes(code))await db.query('INSERT INTO rol_evento(fk_idrol,fk_idevento,permitido,creado_por) VALUES($1,$2,TRUE,$3)',[viewer,e.rows[0].idevento,admin]);}
    for(const [code,name,receipt] of [['EFECTIVO','Efectivo',false],['TRANSFERENCIA','Transferencia',true],['DEPOSITO','Depósito',true],['TARJETA','Tarjeta',true]] as const)await db.query('INSERT INTO forma_pago(codigo,nombre,requiere_comprobante,creado_por) VALUES($1,$2,$3,$4)',[code,name,receipt,admin]);
    for(const name of ['Combustible','Servicios','Mantenimiento','Oficina'])await db.query('INSERT INTO gasto_tipo(nombre,creado_por) VALUES($1,$2)',[name,admin]);
    await db.query(`INSERT INTO configuracion_financiera(interes_minimo,moneda,creado_por) VALUES(10,'PYG',$1)`,[admin]);const owner=(await db.query(`INSERT INTO propietario(nombre_completo,cedula,ruc,direccion,telefono1,email,creado_por) VALUES('Digno Alfredo','2000000','2000000-1','Ciudad del Este','0981000000','admin@prestamos.local',$1) RETURNING idpropietario`,[admin])).rows[0].idpropietario;const bank=(await db.query(`INSERT INTO banco(codigo,nombre,creado_por) VALUES('BNF','Banco Nacional de Fomento',$1) RETURNING idbanco`,[admin])).rows[0].idbanco;await db.query(`INSERT INTO propietario_banco(fk_idpropietario,fk_idbanco,titular,tipo_cuenta,numero_cuenta,moneda,creado_por) VALUES($1,$2,'Digno Alfredo','Ahorro','123456789','PYG',$3)`,[owner,bank,admin]);
    const product=(await db.query(`INSERT INTO producto(codigo,nombre,descripcion,precio_referencia,creado_por) VALUES('MOTO-001','Motocicleta urbana','Producto financiado de demostración',8500000,$1) RETURNING idproducto`,[admin])).rows[0].idproducto;
    const people=[['Pedro Henrique Dias','3000001','0981111111'],['João Santos Pereira','3000002','0981222222'],['María Oliveira','3000003','0981333333'],['Marcos Vinicius Reis','3000004','0981444444'],['Sandra Regina Costa','3000005','0981555555'],['Lucas Martins Rocha','3000006','0981666666']];const clients:number[]=[];
    for(let i=0;i<people.length;i++){const [name,id,phone]=people[i];const c=await db.query(`INSERT INTO cliente(nombre_completo,cedula,direccion,telefono1,email,direccion_trabajo,nombre_empresa,profesion,dedicacion,ingreso_promedio,tasa_interes_sugerida,creado_por) VALUES($1,$2,'Ciudad del Este',$3,$4,'Área comercial','Empresa Demo','Comerciante','Comercio',5000000,10,$5) RETURNING idcliente`,[name,id,phone,`cliente${i+1}@demo.local`,admin]);clients.push(c.rows[0].idcliente);for(let p=1;p<=2;p++)await db.query(`INSERT INTO cliente_referencia(fk_idcliente,posicion,nombre_completo,fk_idtipo_referencia,relacion,telefono,direccion,creado_por) VALUES($1,$2,$3,$4,$5,$6,'Ciudad del Este',$7)`,[c.rows[0].idcliente,p,`Referencia ${p} de ${name}`,p===1?familiarType:amistadType,p===1?'Familiar':'Amistad',`097${i}${p}000000`,admin]);}
    const base=DateTime.now().setZone(config.timezone).startOf('day');
    const demo=[
      {client:clients[0],type:'PRESTAMO' as const,capital:'3000000',rate:'40',count:15,frequency:'DIARIA' as const,start:base.minus({days:3}).toISODate()!,daysWeek:[1,2,3,4,5,6],paid:1},
      {client:clients[1],type:'PRESTAMO' as const,capital:'3000000',rate:'40',count:10,frequency:'SEMANAL' as const,start:base.minus({weeks:7}).toISODate()!,daysWeek:[5],paid:5},
      {client:clients[2],type:'PRESTAMO' as const,capital:'5000000',rate:'40',count:20,frequency:'MENSUAL' as const,start:base.minus({months:11}).toISODate()!,daysMonth:[10],paid:10},
      {client:clients[3],type:'PRESTAMO' as const,capital:'2500000',rate:'30',count:15,frequency:'DIARIA' as const,start:base.minus({days:12}).toISODate()!,daysWeek:[1,2,3,4,5],paid:3},
      {client:clients[4],type:'PRESTAMO' as const,capital:'4500000',rate:'35',count:12,frequency:'QUINCENAL' as const,start:base.minus({months:5}).toISODate()!,daysMonth:[15,30],paid:4},
      {client:clients[5],type:'VENTA_FINANCIADA' as const,capital:'8500000',rate:'20',count:8,frequency:'MENSUAL' as const,start:base.minus({months:2}).toISODate()!,daysMonth:[5],paid:2,product},
    ];
    for(let i=0;i<demo.length;i++){const result=await createDemoOperation(db,admin,demo[i]);if(i===0&&result.loanId)await db.query(`INSERT INTO garantia(fk_idprestamo,fk_idusuario_tasador,tipo_objeto,descripcion,marca,modelo,identificador,valor_aproximado,valor_tasado,creado_por) VALUES($1,$2,'Motocicleta','Motocicleta usada','Kentón','GTR','ABC123',6000000,5000000,$2)`,[result.loanId,admin]);}
    const fuel=(await db.query(`SELECT idgasto_tipo FROM gasto_tipo WHERE nombre='Combustible'`)).rows[0].idgasto_tipo;const expenseDate=base.toISODate()!;const expense=(await db.query(`INSERT INTO gasto(fk_idgasto_tipo,fecha,concepto,monto,observacion,creado_por) VALUES($1,$2,'Combustible para cobranza',180000,'Gasto demo',$3) RETURNING idgasto`,[fuel,expenseDate,admin])).rows[0].idgasto;const cash=await upsertCash(db,expenseDate,admin);await db.query(`INSERT INTO movimiento_caja(fk_idcaja,fk_idgasto,tipo,monto,concepto,fecha_movimiento,creado_por) VALUES($1,$2,'EGRESO',180000,'Combustible para cobranza',$3,$4)`,[cash,expense,`${expenseDate} 09:00:00`,admin]);
    console.log('Demo completa cargada. Usuario: admin@prestamos.local');
  });
}

seed().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>pool.end());
